---
- name: Deploy Helm package to K3s server
  hosts: server
  become: yes
  tasks:

    - name: Check if Helm is already installed
      ansible.builtin.command: helm version --short
      register: helm_check
      ignore_errors: yes

    - name: Install Helm if not present
      ansible.builtin.get_url:
        url: https://get.helm.sh/helm-v3.11.3-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz
      when: helm_check.rc != 0

    - name: Extract Helm binary
      ansible.builtin.unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: yes
      when: helm_check.rc != 0

    - name: Move Helm binary to /usr/local/bin
      ansible.builtin.command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
      when: helm_check.rc != 0

    - name: Copy Helm chart directory to server
      ansible.builtin.copy:
        src: ../../helm/hello-world-app/
        dest: /tmp/hello-world-app/
        mode: preserve  # Optional: Preserve file permissions

    - name: Install Helm package on K3s using Ansible Helm module
      community.kubernetes.helm:
        name: hello-world-app
        chart_ref: /tmp/hello-world-app/   # This can still be the name of the chart
        release_namespace: default
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present

    - name: Display Helm release status
      community.kubernetes.helm_info:
        name: hello-world-app
        release_namespace: default
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: helm_status

    - name: Show Helm installation output
      ansible.builtin.debug:
        var: helm_status